# Generated by Django 2.2.2 on 2019-11-13 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedRecord',
            new_name='LikeRecord',
        ),
    ]
