# Generated by Django 2.2.2 on 2019-10-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191011_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
