# Generated by Django 2.2.2 on 2019-10-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20191020_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
